blog/urls.py
from django.urls import path
from . import views

app_name='blog' # her app içinde ilgili app ismini vermeliyiz routing problemi olmasın dite

urlpatterns = [
    
    path('',views.all_blogs, name="all_blogs"),
    path('<int:blog_id>/',views.detail, name="detail"),
    
    
]


personel_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('blog/', include('blog.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField()
    date=models.DateField()

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=250)
    image=models.ImageField(upload_to='portfolio/images/')
    url=models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

# Create your views here.
def all_blogs(request):
   
    blogs=Blog.objects.order_by('-date')[:5]#son 5 kayıdı gösterir
    return render(request,'blog/all_blogs.html',{'blogs':blogs})

def detail(request,blog_id):
    blog=get_object_or_404(Blog,pk=blog_id)
    return render (request,'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project
# Create your views here.
def home(request):
    projects=Project.objects.all()
    return   render(request,'portfolio/home.html',{'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}

<h2> Nick has written {{blogs.count}} blog</h2>
{% for blog in blogs %}
<a href="{% url 'blog:detail' blog.id %}"><h2>{{blog.title}}</h2></a>
<h5>{{blog.date|date:'M d Y'| upper}}</h5>
<p>{{blog.description|truncatechars:100}}</p>
{% endfor %}

  {% endblock content %}

blog/templates/blog/detail.html

{% extends 'portfolio/base.html' %}
{% block content %}
<h1>{{blog.title}}</h1>
<h2>{{blog.date|date:'M d Y'| upper}}</h2>
<h2>{{blog.description}}</h2>

  {% endblock content %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Hello, world!</title>
  </head>
  <body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block content  %}


{% endblock  %}


  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}


<h1> Hi There!</h1>
<h2>This is the my portfoli Page</h2>

{% load static %}

<a href="{% url 'blog:all_blogs' %}"> Blogs</a>

<img src="{% static 'portfolio/nasa.png' %}"

{% for project in   projects     %}

<h2> {{project.title}}</h2>
<p>{{project.description}}</p>
<img src="{{project.image.url}}" height=40> 
<br>
{%if project.url%}
<a href="{{project.url}}">Link</a>
{% endif %}
{% endfor %}

  {% endblock content %}